services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: cloud_mailserver
    hostname: mail.thekhanj.ir
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - cloud_mailserver_data:/var/mail/
      - cloud_mailserver_state:/var/mail-state/
      - cloud_mailserver_logs:/var/log/mail/
      - cloud_mailserver_config:/tmp/docker-mailserver/
      - ./config/postfix-main.cf:/tmp/docker-mailserver/postfix-main.cf
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      # disable these in favor of rpamd
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0

      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1

      - POSTFIX_INET_PROTOCOLS=ipv4

      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/letsencrypt/live/mail.thekhanj.ir/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/mail.thekhanj.ir/privkey.pem
    cap_add:
      - NET_ADMIN
    restart: always

volumes:
  cloud_mailserver_data:
  cloud_mailserver_state:
  cloud_mailserver_logs:
  cloud_mailserver_config:
